name: diet_schedule_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  circular_chart_flutter: ^0.0.2
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  email_validator: ^2.1.17
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.3.7
  flutter_ruler_picker: null
  flutter_slidable: ^2.0.0
  flutter_time_picker_spinner: ^2.0.0
  google_sign_in: null
  hexcolor: ^3.0.1
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  lottie: ^2.3.1
  pedometer: null
  persistent_bottom_nav_bar: null
  quantity_input: ^1.0.2
  quickalert: ^1.0.1
  rflutter_alert: ^2.0.4
  shimmer: ^2.0.0
  sign_in_button: null
  syncfusion_flutter_charts: null
  syncfusion_flutter_gauges: ^21.1.37

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
